import { Ingredient, AdvantageProduct, Pharmacy } from './types';

export const TRANSLATIONS = {
  tr: {
    nav_collection: 'Koleksiyon',
    nav_ritual: 'Ritüel',
    nav_ingredients: 'İçerikler',
    nav_expert: 'Uzman',
    nav_stores: 'Mağazalar',
    hero_badge: 'Premium Cilt Bakımı',
    hero_title: 'Cildinizi Yeniden Keşfedin',
    hero_subtitle: 'OX SERIES ile bilim ve doğanın mükemmel birleşimi. Üstün formülü ile cildinizin potansiyelini açığa çıkarın.',
    btn_explore: 'Keşfet',
    btn_expert: 'Uzmana Sor',
    btn_share: 'Paylaş',
    btn_copied: 'KOPYALANDI',
    btn_copy_link: 'LİNKİ KOPYALA',
    btn_ingredients: 'İÇERİKLER',
    btn_learn_more: 'DAHA FAZLA BİLGİ',
    btn_show_less: 'DAHA AZ GÖSTER',
    section_ritual: 'Günlük Ritüel',
    ritual_title: '3 Adımda Dönüşüm',
    ritual_subtitle: 'Haftada 2-3 kez uygulayarak cildinizin potansiyelini keşfedin.',
    ritual_step1_title: 'Hazırlık',
    ritual_step1_desc: 'Temiz ve kuru ellere 1 pompa ürün alın. İki ele yayın.',
    ritual_step2_title: 'Uygulama',
    ritual_step2_desc: 'Masaj yaparak yuvarlayın, ölü derilerden kurtulun.',
    ritual_step3_title: 'Arınma',
    ritual_step3_desc: 'Dikkat: Sadece Ilık ve bol su ile durulayın ve nazikçe kurulayın.',
    ritual_time_unit: 'dk',
    ritual_footer_tagline: 'Onaylı Formül • Laboratuvar Testli • OX Premium Standartları',
    ritual_current_focus: 'Güncel Odak Noktası',
    ritual_touch_future: 'Geleceğe Dokunun',
    ingredients_title: 'Formül İçerikleri',
    ingredients_subtitle: 'OX SERIES formülasyonu, her damlada doğanın en saf hallerini ve bilimin en yeni keşiflerini cildinizle buluşturur.',
    expert_title: 'OX Cilt Bakım Uzmanı',
    expert_badge: 'Geleceğe Dokun',
    ai_greeting: 'Merhaba! Ben OX Serum asistanı. Cilt tipinize özel ürün önerileri ve kullanım tavsiyeleri verebilirim.',
    ai_placeholder: 'Cilt tipinizi veya sorununuzu yazın...',
    ai_chip_oily: 'Yağlı Cilt',
    ai_chip_dry: 'Kuru Cilt',
    ai_chip_sensitive: 'Hassas Cilt',
    ai_chip_antiaging: 'Anti-Aging',
    ai_error: 'Bağlantı hatası oluştu.',
    ai_no_response: 'Üzgünüm, şu an cevap veremiyorum.',
    btn_send: 'Gönder',
    advantage_title: 'Advantage Box',
    advantage_desc: 'Fiyat ve marj bilgilerini görmek için profesyonel bayi şifrenizi giriniz.',
    advantage_password_label: 'Özel Erişim Şifresi',
    advantage_password_placeholder: 'Şifreyi giriniz',
    advantage_error: 'Yanlış şifre. Lütfen kontrol edip tekrar deneyiniz.',
    btn_login: 'Giriş Yap',
    btn_cancel: 'İptal',
    btn_logout: 'Güvenli Çıkış',
    price: 'Fiyat',
    margin: 'Marj',
    cost: 'Maliyet',
    profit: 'Kâr',
    product_details_title: 'Ürün Detayları',
    product_quick_view: 'Hızlı Bakış',
    product_net_profit: 'Net Kâr',
    product_request_sample: 'Numune Talep Et',
    footer_copy: '© 2026 OX SERIES. Tüm hakları saklıdır.',
    footer_links_title: 'Hızlı Bağlantılar',
    footer_contact_title: 'İletişim',
    footer_privacy: 'Gizlilik Politikası',
    footer_terms: 'Kullanım Şartları',
    partner_form_title: 'Bayilik Başvurusu',
    pharmacy_name_label: 'Eczane İsmi',
    pharmacy_placeholder: 'Örn: Akasya Eczanesi',
    applicant_name_label: 'Ad Soyad',
    applicant_name_placeholder: 'Adınızı ve soyadınızı giriniz',
    address_label: 'Açık Adres / Konum',
    address_placeholder: 'Eczane adresi veya mahalle bilgisi',
    contact_label: 'İletişim (Tel/E-posta)',
    contact_placeholder: 'Telefon veya E-posta',
    btn_send_location: 'Konum At',
    btn_send_fallback: 'Sadece Bilgileri Gönder (Konumsuz)',
    btn_submit: 'Başvuruyu Gönder',
    btn_register_toggle: 'Bayi Kayıt',
    btn_back: 'Geri',
    location_success: '✓ Konum Alındı',
    form_success: 'Başvurunuz başarıyla iletildi. En kısa sürede iletişime geçeceğiz.',
    form_success_sub: 'Telegram üzerinden bilgilendirme iletildi.',
    partner_advantage_title: 'Partner Avantajları',
    stores_title: 'Size En Yakın Noktalar',
    btn_locate: 'Bul',
    btn_locating: 'ARANIYOR...',
    pharmacy_empty: 'Çevrenizdeki eczaneleri görmek için konum izni verin ve butona tıklayın.',
    pharmacy_in_stock: 'STOKTA VAR',
    pharmacy_out_of_stock: 'TÜKENDİ',
    pharmacy_distance: 'Mesafe',
    pharmacy_directions: 'Yol Tarifi Al',
    example_badge: 'Örnek Adres',
    app_request_title: 'UZMAN BAŞVURUSU',
    app_request_subtitle: 'Protokol V2.0',
    app_request_desc: 'Eczanenizde profesyonel uygulama etkinliği planlamak için formu doldurun.',
    app_time_label: 'Uygulama Saati',
    app_time_placeholder: 'Örn: 14:00 - 16:00',
    btn_request_app: 'Uygulama Talep Et',
    app_protocol_badge: 'Protokol Ox Series',
    app_exclusive_badge: 'Özel',
    form_missing: 'Lütfen tüm alanları doldurunuz.',
    form_processing: 'İşleniyor...',
    location_error: 'Konum alınamadı.',
    technical_overview: 'Teknik Genel Bakış',
    btn_view_formula: 'FORMÜLÜ İNCELE',
    volume: 'Hacim',
    sku: 'Ürün Kodu',
    role_label: 'Yetki Ünvanı',
    role_pharmacist: 'Eczacı',
    role_assistant: 'Eczacı Kalfası',
    label_quantity: 'Adet',
    label_mf: 'MF'
  },
  en: {
    nav_collection: 'Collection',
    nav_ritual: 'Ritual',
    nav_ingredients: 'Ingredients',
    nav_expert: 'Expert',
    nav_stores: 'Stores',
    hero_badge: 'Premium Skincare',
    hero_title: 'Rediscover Your Skin',
    hero_subtitle: 'With OX SERIES, the perfect blend of science and nature. Unlock your skin\'s potential with our advanced formula.',
    btn_explore: 'Explore',
    btn_expert: 'Ask Expert',
    btn_share: 'Share',
    btn_copied: 'COPIED',
    btn_copy_link: 'COPY LINK',
    btn_ingredients: 'INGREDIENTS',
    btn_learn_more: 'LEARN MORE',
    btn_show_less: 'SHOW LESS',
    section_ritual: 'Daily Ritual',
    ritual_title: '3-Step Transformation',
    ritual_subtitle: 'Apply 2-3 times per week to discover your skin\'s potential.',
    ritual_step1_title: 'Preparation',
    ritual_step1_desc: 'Apply 1 pump to clean, dry hands. Spread on both hands.',
    ritual_step2_title: 'Application',
    ritual_step2_desc: 'Massage and roll to get rid of dead skin cells.',
    ritual_step3_title: 'Rinse',
    ritual_step3_desc: 'Attention: Rinse only with lukewarm and plenty of water, then dry gently.',
    ritual_time_unit: 'min',
    ritual_footer_tagline: 'Certified Formula • Laboratory Tested • OX Premium Standards',
    ritual_current_focus: 'Current Focus',
    ritual_touch_future: 'Touch the Future',
    ingredients_title: 'Formula Ingredients',
    ingredients_subtitle: 'OX SERIES formulation brings the purest forms of nature and latest scientific discoveries to your skin.',
    expert_title: 'OX Skincare Expert',
    expert_badge: 'Touch the Future',
    ai_greeting: 'Hello! I\'m the OX Serum assistant. I can provide personalized product recommendations and usage advice based on your skin type.',
    ai_placeholder: 'Type your skin type or concern...',
    ai_chip_oily: 'Oily Skin',
    ai_chip_dry: 'Dry Skin',
    ai_chip_sensitive: 'Sensitive Skin',
    ai_chip_antiaging: 'Anti-Aging',
    ai_error: 'Connection error occurred.',
    ai_no_response: 'Sorry, I am unable to answer right now.',
    btn_send: 'Send',
    advantage_title: 'Advantage Box',
    advantage_desc: 'Enter your professional partner password to view price and margin details.',
    advantage_password_label: 'Private Access Password',
    advantage_password_placeholder: 'Enter password',
    advantage_error: 'Incorrect password. Please check and try again.',
    btn_login: 'Login',
    btn_cancel: 'Cancel',
    btn_logout: 'Logout',
    price: 'Price',
    margin: 'Margin',
    cost: 'Cost',
    profit: 'Profit',
    product_details_title: 'Product Details',
    product_quick_view: 'Quick View',
    product_net_profit: 'Net Profit',
    product_request_sample: 'Request Sample',
    footer_copy: '© 2026 OX SERIES. All rights reserved.',
    footer_links_title: 'Quick Links',
    footer_contact_title: 'Contact',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Use',
    partner_form_title: 'Partnership Application',
    pharmacy_name_label: 'Pharmacy Name',
    pharmacy_placeholder: 'e.g. Acacia Pharmacy',
    applicant_name_label: 'Full Name',
    applicant_name_placeholder: 'Enter your full name',
    address_label: 'Address / Location',
    address_placeholder: 'Pharmacy address or area info',
    contact_label: 'Contact Info (Tel/Email)',
    contact_placeholder: 'Phone or Email',
    btn_send_location: 'Share Location',
    btn_send_fallback: 'Send Info Only (No Location)',
    btn_submit: 'Submit Application',
    btn_request_app: 'Request Application',
    btn_register_toggle: 'Partner Register',
    btn_back: 'Back',
    location_success: '✓ Location Received',
    form_success: 'Your application has been sent successfully. We will contact you soon.',
    form_success_sub: 'Notification sent via Telegram.',
    partner_advantage_title: 'Partner Advantages',
    stores_title: 'Find Closest Points',
    btn_locate: 'Find',
    btn_locating: 'LOCATING...',
    pharmacy_empty: 'Please allow location access and click the button to see nearby pharmacies.',
    pharmacy_in_stock: 'IN STOCK',
    pharmacy_out_of_stock: 'OUT OF STOCK',
    pharmacy_distance: 'Distance',
    pharmacy_directions: 'Get Directions',
    example_badge: 'Example Address',
    app_request_title: 'EXPERT APPLICATION',
    app_request_subtitle: 'Protocol V2.0',
    app_request_desc: 'Fill in the form to schedule a professional application event at your pharmacy.',
    app_time_label: 'Application Time',
    app_time_placeholder: 'e.g. 2:00 PM - 4:00 PM',
    app_protocol_badge: 'Protocol Ox',
    app_exclusive_badge: 'Exclusive Series',
    form_missing: 'Please fill in all fields.',
    form_processing: 'Processing...',
    location_error: 'Location could not be retrieved.',
    technical_overview: 'Technical Overview',
    btn_view_formula: 'VIEW FORMULA',
    volume: 'Volume',
    sku: 'SKU',
    role_label: 'Authority Title',
    role_pharmacist: 'Pharmacist',
    role_assistant: 'Pharmacy Assistant',
    label_quantity: 'QTY',
    label_mf: 'MF'
  }
};

export const EXCELLENCE_V2_INGREDIENTS = [
  "Hydrolyzed Collagen",
  "Helianthus Annuus Seed Oil",
  "Prunus Cerasus Seed Oil",
  "Ranunculus Ficaria Extract",
  "Persea Gratissima Oil",
  "Calendula Officinalis Seed Oil",
  "Caprylic/Capric Triglyceride",
  "Panthenol",
  "Polysorbate 20",
  "Lavandula Angustifolia Oil",
  "Tocopheryl Acetate",
  "Resveratrol"
];

export const AUTHORIZED_PHARMACIES: Pharmacy[] = [
  { 
    name: "OX Boutique Pharmacy (Örnek)", 
    distance: "0.0", 
    inStock: true, 
    lat: 38.4357, 
    lng: 27.1394 
  }
];

export const INGREDIENTS_SERUM_TR: Ingredient[] = [
  { name: 'Hidrolize Kolajen', concentration: 'Ana', description: 'Cilt elastikiyetini artıran ve kırışıklıkları azaltan güçlü protein kompleksi.', origin: 'Sığır Kaynaklı' },
  { name: 'Ayçiçek Çekirdeği Yağı', concentration: 'Aktif', description: 'Cildi doğal yollarla besleyen, yumuşatan ve nemlendiren yağ.', origin: 'Bitkisel' },
  { name: 'Vişne Çekirdeği Yağı', concentration: 'Aktif', description: 'Antioksidan özellikleri ile cildi dış etkenlere karşı korur.', origin: 'Bitkisel' },
  { name: 'Ranunculus Ficaria Özü', concentration: 'Aktif', description: 'Kan dolaşımını düzenlemeye yardımcı olan doğal ekstrakt.', origin: 'Bitkisel' },
  { name: 'Avokado Yağı', concentration: 'Aktif', description: 'Derinlemesine besleyici. A, D ve E vitaminleri bakımından zengindir.', origin: 'Bitkisel' },
  { name: 'Pantenol B5', concentration: 'B5', description: 'Pro-vitamin B5, cildi nemlendirir ve iyileşme sürecini destekler.', origin: 'Vitamin' },
  { name: 'Resveratrol', concentration: 'Aktif', description: 'Üzümde bulunan doğal antioksidan. Genç görünümü destekler.', origin: 'Bitkisel' }
];

export const INGREDIENTS_VEGAN_SERUM_TR: Ingredient[] = [
  { name: 'Helianthus Annuus Seed Oil', concentration: 'Aktif', description: 'Ayçiçek yağı. Cildi nemlendirir ve E vitamini açısından zengindir.', origin: 'Bitkisel' },
  { name: 'Prunus Cerasus Seed Oil', concentration: 'Aktif', description: 'Vişne çekirdeği yağı. Antioksidan özelliklere sahiptir.', origin: 'Bitkisel' },
  { name: 'Persea Gratissima Oil', concentration: 'Aktif', description: 'Avokado yağı. Çok besleyicidir, kuru ciltler için idealdir.', origin: 'Bitkisel' },
  { name: 'Cyclopentasiloxane', concentration: 'Doku', description: 'Ciltte ipeksi bir his bırakmasını ve kolay yayılmasını sağlar.', origin: 'Sentetik' },
  { name: 'Tocopheryl Acetate', concentration: 'Vitamin', description: 'E vitamini türevidir. Cildi dış etkenlere karşı koruyan güçlü bir antioksidandır.', origin: 'Vitamin' },
  { name: 'Panthenol', concentration: 'B5', description: 'Cildi onarır, nem tutma kapasitesini artırır ve yatıştırır.', origin: 'Vitamin' },
  { name: 'Caprylic/Capric Triglyceride', concentration: 'Pürüzsüzleştirici', description: 'Hindistan cevizi yağı ve gliserinden elde edilen, cildi pürüzsüzleştiren madde.', origin: 'Bitkisel' },
  { name: 'Lavandula Angustifolia Oil', concentration: 'Yatıştırıcı', description: 'Lavanta yağı. Yatıştırıcı etkisi ve hoş kokusu için eklenir.', origin: 'Bitkisel' },
  { name: 'Ranunculus Ficaria Extract', concentration: 'Aktif', description: 'Basur otu özü. Yatıştırıcı ve damar büzücü özellikler.', origin: 'Bitkisel' }
];

export const INGREDIENTS_SERUM_EN: Ingredient[] = [
  { name: 'Hydrolyzed Collagen', concentration: 'Main', description: 'Powerful protein complex that increases skin elasticity and reduces wrinkles.', origin: 'Bovine source' },
  { name: 'Sunflower Seed Oil', concentration: 'Active', description: 'Nourishes, softens, and hydrates naturally.', origin: 'Plant-based' },
  { name: 'Cherry Seed Oil', concentration: 'Active', description: 'Protects skin with antioxidant properties.', origin: 'Plant-based' },
  { name: 'Ranunculus Ficaria Extract', concentration: 'Active', description: 'Helps improve blood circulation.', origin: 'Plant-based' },
  { name: 'Avocado Oil', concentration: 'Active', description: 'Deeply nourishes. Rich in Vitamins A, D, and E.', origin: 'Plant-based' },
  { name: 'Panthenol B5', concentration: 'B5', description: 'Pro-vitamin B5 moisturizes and supports the healing process.', origin: 'Vitamin' },
  { name: 'Resveratrol', concentration: 'Active', description: 'Natural antioxidant found in grapes. Supports youthfulness.', origin: 'Plant-based' }
];

export const INGREDIENTS_CLEANSER_TR: Ingredient[] = [
  { name: 'Sodyum Hyaluronat', concentration: 'Nem', description: 'Cildi kurutmadan temizleyen yoğun nem çekici.', origin: 'Laboratuvar' },
  { name: 'Aloe Vera Özü', concentration: 'Sakinlik', description: 'Temizlik sırasında cildi yatıştıran doğal bileşen.', origin: 'Bitkisel' }
];

export const INGREDIENTS_MOISTURIZER_TR: Ingredient[] = [
  { name: 'Seramid Kompleksi', concentration: 'Bariyer', description: 'Cilt bariyerini güçlendiren yapısal yağlar.', origin: 'Biyoteknoloji' },
  { name: 'Niasinamid', concentration: 'Vitamin', description: 'Cilt tonunu düzenleyen ve gözenekleri küçülten B3 vitamini.', origin: 'Vitamin' }
];

// For backward compatibility and the main Ingredients section
export const INGREDIENTS_TR = INGREDIENTS_SERUM_TR;
export const INGREDIENTS_EN = INGREDIENTS_SERUM_EN;

export const ADVANTAGE_PRODUCTS: AdvantageProduct[] = [
  { 
    name: 'OX Serum Peeling', 
    emoji: '✨', 
    image: 'https://lh3.googleusercontent.com/d/17owdBi-AIhNyVOuv7gxbmmnUe40mdUKQ', 
    price: '₺1.500', 
    margin: '%60', 
    cost: '₺700', 
    profit: '850',
    volume: '50ml',
    sku: 'OX-SP-001',
    description: 'Improves skin elasticity with collagen-based rolling exfoliation technology.',
    detailedDescription: 'The OX Serum Peeling is our flagship product, utilizing a breakthrough collagen-based rolling formula. Attention: Rinse only with lukewarm and plenty of water, then dry gently. Ideal for achieving a "glass skin" finish and prepping for deeper hydration.'
  },
  { 
    name: 'Gel Cleanser', 
    emoji: '🧼', 
    image: 'https://lh3.googleusercontent.com/d/1Nc9QyAtSmQvCmpV7ViIPKL8Z8lGvxwyz', 
    price: '₺1.000', 
    margin: '%60', 
    cost: '₺650', 
    profit: '350',
    volume: '200ml',
    sku: 'OX-GC-002',
    description: 'Gentle pH-balanced cleanser that removes impurities without stripping moisture.',
    detailedDescription: 'Specifically formulated to complement the OX Series ritual, this Gel Cleanser provides a deep yet extremely gentle cleanse. It effectively removes environmental pollutants and makeup residues while maintaining the skin\'s natural pH balance. Infused with botanical extracts to soothe and refresh the complexion.'
  },
  { 
    name: 'Moisturizing Cream', 
    emoji: '💧', 
    image: 'https://lh3.googleusercontent.com/d/1nU5dkT-pob8_wMNWtkdJKHfJ3slWLm0h', 
    price: '₺1.500', 
    margin: '%20', 
    cost: '₺680', 
    profit: '820',
    volume: '50ml',
    sku: 'OX-MC-003',
    description: 'Intensive hydration barrier with high concentration of collagen and Panthenol B5.',
    detailedDescription: 'This luxury Moisturizing Cream acts as a secondary barrier, locking in the potent active ingredients from your serum. With a high concentration of Panthenol B5 and ultra-pure Hydrolyzed Collagen, it provides 24-hour hydration and visible plumping effects, leaving the skin feeling velvet-soft and resilient.'
  },
  { 
    name: 'Vegan Anti Aging Serum', 
    emoji: '🌿', 
    image: 'https://lh3.googleusercontent.com/d/1CJX6_VHAZI0UHGZkI_ecnnEqj1eq3xK8', 
    secondaryImage: 'https://lh3.googleusercontent.com/d/1PLEBgKjbF9fY6utwpl-placeholder',
    price: '₺1.500',
    margin: '%60',
    cost: '₺650',
    profit: '850',
    volume: '30ml',
    sku: 'OX-VS-004',
    description: '100% plant-based formulation for advanced skin rejuvenation.',
    detailedDescription: 'The Vegan Anti Aging Serum is a masterclass in plant-based biotechnology. Using premium botanical extracts and non-animal collagen alternatives, it targets fine lines and loss of firmness without compromising on ethical standards. Perfect for all skin types, especially sensitive skin seeking powerful results.'
  }
];