import { AdvantageProduct, Pharmacy } from './types';

export const TRANSLATIONS = {
  tr: {
    nav_collection: 'Koleksiyon',
    nav_ritual: 'Ritüel',
    nav_technical_sheet: 'Teknik Belge',
    nav_stores: 'Mağazalar',
    hero_badge: 'Premium Cilt Bakımı',
    hero_title: 'Cildinizi Yeniden Keşfedin',
    hero_subtitle: 'OX SERIES ile bilim ve doğanın mükemmel birleşimi. Üstün formülü ile cildinizin potansiyelini açığa çıkarın.',
    btn_explore: 'Keşfet',
    btn_expert: 'Uzmana Sor',
    btn_share: 'Paylaş',
    btn_copied: 'KOPYALANDI',
    btn_copy_link: 'LİNKİ KOPYALA',
    btn_ingredients: 'İÇERİKLER',
    btn_learn_more: 'DAHA FAZLA BİLGİ',
    btn_show_less: 'DAHA AZ GÖSTER',
    section_ritual: 'Günlük Ritüel',
    ritual_title: '3 Adımda Dönüşüm',
    ritual_subtitle: 'Haftada 2-3 kez uygulayarak cildinizin potansiyelini keşfedin.',
    ritual_step1_title: 'Hazırlık',
    ritual_step1_desc: 'Temiz ve kuru ellere 1 pompa ürün alın. İki ele yayın.',
    ritual_step2_title: 'Uygulama',
    ritual_step2_desc: 'Masaj yaparak yuvarlayın, ölü derilerden kurtulun.',
    ritual_step3_title: 'Arınma',
    ritual_step3_desc: 'Dikkat: Sadece Ilık ve bol su ile durulayın ve nazikçe kurulayın.',
    ritual_time_unit: 'dk',
    ritual_footer_tagline: 'Onaylı Formül • Laboratuvar Testli • OX Premium Standartları',
    ritual_current_focus: 'Güncel Odak Noktası',
    ritual_touch_future: 'Geleceğe Dokunun',
    expert_badge: 'Geleceğe Dokun',
    btn_send: 'Gönder',
    advantage_title: 'Advantage Box',
    advantage_desc: 'Fiyat ve marj bilgilerini görmek için profesyonel bayi şifrenizi giriniz.',
    advantage_password_label: 'Özel Erişim Şifresi',
    advantage_password_placeholder: 'Şifreyi giriniz',
    advantage_error: 'Yanlış şifre. Lütfen kontrol edip tekrar deneyiniz.',
    btn_login: 'Giriş Yap',
    btn_cancel: 'İptal',
    btn_logout: 'Güvenli Çıkış',
    price: 'Fiyat',
    margin: 'Marj',
    cost: 'Maliyet',
    profit: 'Kâr',
    product_details_title: 'Ürün Detayları',
    product_quick_view: 'Hızlı Bakış',
    product_net_profit: 'Net Kâr',
    product_request_sample: 'Numune Talep Et',
    footer_copy: '© 2026 OX SERIES. Tüm hakları saklıdır.',
    footer_links_title: 'Hızlı Bağlantılar',
    footer_contact_title: 'İletişim',
    footer_privacy: 'Gizlilik Politikası',
    footer_terms: 'Kullanım Şartları',
    partner_form_title: 'Bayilik Başvurusu',
    pharmacy_name_label: 'Eczane İsmi',
    pharmacy_placeholder: 'Örn: Akasya Eczanesi',
    applicant_name_label: 'Ad Soyad',
    applicant_name_placeholder: 'Adınızı ve soyadınızı giriniz',
    address_label: 'Açık Adres / Konum',
    address_placeholder: 'Eczane adresi veya mahalle bilgisi',
    contact_label: 'İletişim (Tel/E-posta)',
    contact_placeholder: 'Telefon veya E-posta',
    btn_send_location: 'Konum At',
    btn_send_fallback: 'Sadece Bilgileri Gönder (Konumsuz)',
    btn_submit: 'Başvuruyu Gönder',
    btn_register_toggle: 'Bayi Kayıt',
    btn_back: 'Geri',
    location_success: '✓ Konum Alındı',
    form_success: 'Başvurunuz başarıyla iletildi. En kısa sürede iletişime geçeceğiz.',
    form_success_sub: 'Telegram üzerinden bilgilendirme iletildi.',
    partner_advantage_title: 'Partner Avantajları',
    stores_title: 'Size En Yakın Noktalar',
    btn_locate: 'Bul',
    btn_locating: 'ARANIYOR...',
    pharmacy_empty: 'Çevrenizdeki eczaneleri görmek için konum izni verin ve butona tıklayın.',
    pharmacy_in_stock: 'STOKTA VAR',
    pharmacy_out_of_stock: 'TÜKENDİ',
    pharmacy_distance: 'Mesafe',
    pharmacy_directions: 'Yol Tarifi Al',
    example_badge: 'Örnek Adres',
    app_request_title: 'UZMAN BAŞVURUSU',
    app_request_subtitle: 'Protokol V2.0',
    app_request_desc: 'Eczanenizde profesyonel uygulama etkinliği planlamak için formu doldurun.',
    app_time_label: 'Uygulama Saati',
    app_time_placeholder: 'Örn: 14:00 - 16:00',
    btn_request_app: 'Uygulama Talep Et',
    app_protocol_badge: 'Protokol Ox Series',
    app_exclusive_badge: 'Özel',
    form_missing: 'Lütfen tüm alanları doldurunuz.',
    form_processing: 'İşleniyor...',
    location_error: 'Konum alınamadı.',
    technical_overview: 'Teknik Genel Bakış',
    btn_view_formula: 'FORMÜLÜ İNCELE',
    volume: 'Hacim',
    sku: 'Ürün Kodu',
    role_label: 'Yetki Ünvanı',
    role_pharmacist: 'Eczacı',
    role_assistant: 'Eczacı Kalfası',
    label_quantity: 'Adet',
    label_mf: 'MF',
    technical_sheet_title: 'Technical Sheet',
    technical_sheet_formula: 'Formula Ox Series',
    technical_sheet_product: 'Collagen Peeling'
  },
  en: {
    nav_collection: 'Collection',
    nav_ritual: 'Ritual',
    nav_technical_sheet: 'Technical Sheet',
    nav_stores: 'Stores',
    hero_badge: 'Premium Skincare',
    hero_title: 'Rediscover Your Skin',
    hero_subtitle: 'With OX SERIES, the perfect blend of science and nature. Unlock your skin\'s potential with our advanced formula.',
    btn_explore: 'Explore',
    btn_expert: 'Ask Expert',
    btn_share: 'Share',
    btn_copied: 'COPIED',
    btn_copy_link: 'COPY LINK',
    btn_ingredients: 'INGREDIENTS',
    btn_learn_more: 'LEARN MORE',
    btn_show_less: 'SHOW LESS',
    section_ritual: 'Daily Ritual',
    ritual_title: '3-Step Transformation',
    ritual_subtitle: 'Apply 2-3 times per week to discover your skin\'s potential.',
    ritual_step1_title: 'Preparation',
    ritual_step1_desc: 'Apply 1 pump to clean, dry hands. Spread on both hands.',
    ritual_step2_title: 'Application',
    ritual_step2_desc: 'Massage and roll to get rid of dead skin cells.',
    ritual_step3_title: 'Rinse',
    ritual_step3_desc: 'Attention: Rinse only with lukewarm and plenty of water, then dry gently.',
    ritual_time_unit: 'min',
    ritual_footer_tagline: 'Certified Formula • Laboratory Tested • OX Premium Standards',
    ritual_current_focus: 'Current Focus',
    ritual_touch_future: 'Touch the Future',
    expert_badge: 'Touch the Future',
    btn_send: 'Send',
    advantage_title: 'Advantage Box',
    advantage_desc: 'Enter your professional partner password to view price and margin details.',
    advantage_password_label: 'Private Access Password',
    advantage_password_placeholder: 'Enter password',
    advantage_error: 'Incorrect password. Please check and try again.',
    btn_login: 'Login',
    btn_cancel: 'Cancel',
    btn_logout: 'Logout',
    price: 'Price',
    margin: 'Margin',
    cost: 'Cost',
    profit: 'Profit',
    product_details_title: 'Product Details',
    product_quick_view: 'Quick View',
    product_net_profit: 'Net Profit',
    product_request_sample: 'Request Sample',
    footer_copy: '© 2026 OX SERIES. All rights reserved.',
    footer_links_title: 'Quick Links',
    footer_contact_title: 'Contact',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Use',
    partner_form_title: 'Partnership Application',
    pharmacy_name_label: 'Pharmacy Name',
    pharmacy_placeholder: 'e.g. Acacia Pharmacy',
    applicant_name_label: 'Full Name',
    applicant_name_placeholder: 'Enter your full name',
    address_label: 'Address / Location',
    address_placeholder: 'Pharmacy address or area info',
    contact_label: 'Contact Info (Tel/Email)',
    contact_placeholder: 'Phone or Email',
    btn_send_location: 'Share Location',
    btn_send_fallback: 'Send Info Only (No Location)',
    btn_submit: 'Submit Application',
    btn_request_app: 'Request Application',
    btn_register_toggle: 'Partner Register',
    btn_back: 'Back',
    location_success: '✓ Location Received',
    form_success: 'Your application has been sent successfully. We will contact you soon.',
    form_success_sub: 'Notification sent via Telegram.',
    partner_advantage_title: 'Partner Advantages',
    stores_title: 'Find Closest Points',
    btn_locate: 'Find',
    btn_locating: 'LOCATING...',
    pharmacy_empty: 'Please allow location access and click the button to see nearby pharmacies.',
    pharmacy_in_stock: 'IN STOCK',
    pharmacy_out_of_stock: 'OUT OF STOCK',
    pharmacy_distance: 'Distance',
    pharmacy_directions: 'Get Directions',
    example_badge: 'Example Address',
    app_request_title: 'EXPERT APPLICATION',
    app_request_subtitle: 'Protocol V2.0',
    app_request_desc: 'Fill in the form to schedule a professional application event at your pharmacy.',
    app_time_label: 'Application Time',
    app_time_placeholder: 'e.g. 2:00 PM - 4:00 PM',
    app_protocol_badge: 'Protocol Ox',
    app_exclusive_badge: 'Exclusive Series',
    form_missing: 'Please fill in all fields.',
    form_processing: 'Processing...',
    location_error: 'Location could not be retrieved.',
    technical_overview: 'Technical Overview',
    btn_view_formula: 'VIEW FORMULA',
    volume: 'Volume',
    sku: 'SKU',
    role_label: 'Authority Title',
    role_pharmacist: 'Pharmacist',
    role_assistant: 'Pharmacy Assistant',
    label_quantity: 'QTY',
    label_mf: 'MF',
    technical_sheet_title: 'Technical Sheet',
    technical_sheet_formula: 'Formula Ox Series',
    technical_sheet_product: 'Collagen Peeling'
  }
};

export const EXCELLENCE_V2_INGREDIENTS = [
  "Hydrolyzed Collagen",
  "Helianthus Annuus Seed Oil",
  "Prunus Cerasus Seed Oil",
  "Ranunculus Ficaria Extract",
  "Persea Gratissima Oil",
  "Calendula Officinalis Seed Oil",
  "Caprylic/Capric Triglyceride",
  "Panthenol",
  "Polysorbate 20",
  "Lavandula Angustifolia Oil",
  "Tocopheryl Acetate",
  "Resveratrol"
];

export const AUTHORIZED_PHARMACIES: Pharmacy[] = [
  { 
    name: "OX Boutique Pharmacy (Örnek)", 
    distance: "0.0", 
    inStock: true, 
    lat: 38.4357, 
    lng: 27.1394 
  }
];

export const ADVANTAGE_PRODUCTS: AdvantageProduct[] = [
  { 
    name: 'OX Serum Peeling', 
    emoji: '✨', 
    image: 'https://lh3.googleusercontent.com/d/17owdBi-AIhNyVOuv7gxbmmnUe40mdUKQ', 
    price: '₺1.050', 
    margin: '%50', 
    cost: '₺ 624 ( Kdv dahil )', 
    profit: '++ 626',
    volume: '50ml',
    sku: 'OX-SP-001',
    description: 'Improves skin elasticity with collagen-based rolling exfoliation technology.',
    detailedDescription: 'The OX Serum Peeling is our flagship product, utilizing a breakthrough collagen-based rolling formula. Attention: Rinse only with lukewarm and plenty of water, then dry gently. Ideal for achieving a "glass skin" finish and prepping for deeper hydration.',
    technicalSheet: {
      batch: 'OX-2026-V2',
      origin: 'Premium',
      status: 'Verified',
      type: 'Serum',
      formula: 'Formula Ox Series',
      productName: 'Collagen Peeling'
    }
  },
  { 
    name: 'Gel Cleanser', 
    emoji: '🧼', 
    image: 'https://lh3.googleusercontent.com/d/1Nc9QyAtSmQvCmpV7ViIPKL8Z8lGvxwyz', 
    price: '₺ 850', 
    margin: '%50', 
    cost: '₺432 ( Kdv dahil )', 
    profit: '418',
    volume: '200ml',
    sku: 'OX-GC-002',
    description: 'Gentle pH-balanced cleanser that removes impurities without stripping moisture.',
    detailedDescription: 'Specifically formulated to complement the OX Series ritual, this Gel Cleanser provides a deep yet extremely gentle cleanse. It effectively removes environmental pollutants and makeup residues while maintaining the skin\'s natural pH balance. Infused with botanical extracts to soothe and refresh the complexion.'
  },
  { 
    name: 'Moisturizing Cream', 
    emoji: '💧', 
    image: 'https://lh3.googleusercontent.com/d/1nU5dkT-pob8_wMNWtkdJKHfJ3slWLm0h', 
    price: '₺2.400', 
    margin: '%60', 
    cost: '₺1.140 ( Kdv dahil )', 
    profit: '1.450',
    volume: '50ml',
    sku: 'OX-MC-003',
    description: 'Intensive hydration barrier with high concentration of collagen and Panthenol B5.',
    detailedDescription: 'This luxury Moisturizing Cream acts as a secondary barrier, locking in the potent active ingredients from your serum. With a high concentration of Panthenol B5 and ultra-pure Hydrolyzed Collagen, it provides 24-hour hydration and visible plumping effects, leaving the skin feeling velvet-soft and resilient.'
  },
  { 
    name: 'Vegan Anti Aging Serum', 
    emoji: '🌿', 
    image: 'https://lh3.googleusercontent.com/d/1CJX6_VHAZI0UHGZkI_ecnnEqj1eq3xK8', 
    secondaryImage: 'https://lh3.googleusercontent.com/d/1PLEBgKjbF9fY6utwpl-placeholder',
    price: '₺1.050',
    margin: '%50',
    cost: '₺ 525 ( Kdv dahil )',
    profit: '+668',
    volume: '30ml',
    sku: 'OX-VS-004',
    description: '100% plant-based formulation for advanced skin rejuvenation.',
    detailedDescription: 'The Vegan Anti Aging Serum is a masterclass in plant-based biotechnology. Using premium botanical extracts and non-animal collagen alternatives, it targets fine lines and loss of firmness without compromising on ethical standards. Perfect for all skin types, especially sensitive skin seeking powerful results.'
  }
];